import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';

// Providers
import ReduxProvider from '@/providers/reduxProvider';
import { TanstackProvider } from '@/providers/tanstackProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <TanstackProvider>
            <Header />
              {children}
            <Footer />
          </TanstackProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
